export const styles = {
  root: {
    width: "100%",
    height: "100vh",
    margin: 0,
    padding: 0,
    fontFamily: '"Inter", -apple-system, sans-serif',
    background: "#020617",
    color: "#f1f5f9",
    overflow: "hidden",
    position: "relative",
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 24px",
    zIndex: 10,
    background: "linear-gradient(180deg, rgba(2,6,23,0.85) 0%, rgba(2,6,23,0) 100%)",
  },
  brand: {
    fontSize: 20,
    fontWeight: 600,
    letterSpacing: "-0.02em",
  },
  viewToggle: {
    display: "flex",
    gap: 4,
    background: "rgba(30,41,59,0.6)",
    padding: 3,
    borderRadius: 8,
    border: "1px solid rgba(148,163,184,0.15)",
  },
  toggleBtn: {
    background: "transparent",
    border: "none",
    color: "#94a3b8",
    padding: "6px 14px",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    transition: "all 0.2s",
  },
  toggleBtnActive: {
    background: "#6366f1",
    color: "#ffffff",
  },
  canvasContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  tabsBar: {
    position: "absolute",
    top: 70,
    left: 24,
    display: "flex",
    gap: 6,
    zIndex: 5,
  },
  tabBtn: {
    background: "rgba(30,41,59,0.7)",
    border: "1px solid rgba(148,163,184,0.15)",
    color: "#cbd5e1",
    padding: "8px 16px",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.05em",
    backdropFilter: "blur(10px)",
  },
  tabBtnActive: {
    background: "#6366f1",
    color: "#ffffff",
    borderColor: "#6366f1",
  },
  sidePanel: {
    position: "absolute",
    top: 120,
    left: 24,
    width: 340,
    maxHeight: "calc(100vh - 160px)",
    overflowY: "auto",
    background: "rgba(15,23,42,0.85)",
    border: "1px solid rgba(148,163,184,0.15)",
    borderRadius: 12,
    backdropFilter: "blur(14px)",
    zIndex: 5,
  },
  panelContent: {
    padding: 24,
  },
  panelHeading: {
    fontSize: 22,
    fontWeight: 600,
    margin: "0 0 16px 0",
    letterSpacing: "-0.02em",
  },
  panelSubheading: {
    fontSize: 13,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "#94a3b8",
    margin: "20px 0 8px 0",
  },
  panelText: {
    fontSize: 14,
    lineHeight: 1.6,
    color: "#cbd5e1",
    margin: "0 0 10px 0",
  },
  panelList: {
    fontSize: 14,
    lineHeight: 1.8,
    color: "#cbd5e1",
    paddingLeft: 20,
    margin: 0,
  },
  projectCard: {
    padding: "12px 14px",
    marginBottom: 10,
    background: "rgba(30,41,59,0.6)",
    borderRadius: 8,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  closeButton: {
    background: "transparent",
    border: "none",
    color: "#94a3b8",
    cursor: "pointer",
    fontSize: 13,
    padding: 0,
    marginBottom: 12,
  },
  hint: {
    position: "absolute",
    bottom: 20,
    right: 24,
    fontSize: 12,
    color: "#64748b",
    zIndex: 5,
  },
  classicWrapper: {
    width: "100%",
    height: "100vh",
    overflowY: "auto",
    background: "#ffffff",
    color: "#0f172a",
  },
  classicInner: {
    maxWidth: 720,
    margin: "0 auto",
    padding: "80px 32px 64px",
  },
  classicH1: {
    fontSize: 44,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    margin: 0,
  },
  classicLead: {
    fontSize: 18,
    color: "#475569",
    marginTop: 8,
  },
  classicH2: {
    fontSize: 22,
    fontWeight: 600,
    borderBottom: "1px solid #e2e8f0",
    paddingBottom: 8,
    marginBottom: 16,
  },
  classicH3: {
    fontSize: 17,
    fontWeight: 600,
    margin: "0 0 4px 0",
  },
  classicText: {
    fontSize: 15,
    lineHeight: 1.7,
    color: "#334155",
  },
  classicCard: {
    padding: "16px 0",
    borderBottom: "1px solid #f1f5f9",
  },
};
